name: test

on:
  push:
    tags:
      - "*"
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 6 * * *" # Daily at 6 AM UTC
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout repository (without ref first)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # We need all tags to detect the latest

      - name: Determine latest tag
        id: get_latest_tag
        run: |
          TAG=$(git describe --tags "$(git rev-list --tags --max-count=1)")
          echo "Latest tag is $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Checkout latest tag if schedule
        if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
        run: |
          git fetch --tags
          git checkout ${{ steps.get_latest_tag.outputs.tag }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: server/package-lock.json

      - name: Debug files
        run: |
          pwd
          ls -la
          git status
          git describe --tags || echo "No tag found"

      - name: Install dependencies
        run: npm install

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-6 libxcomposite1 libxcursor1 libxdamage1 libxext6 \
            libxfixes3 libxi6 libxtst6 libnss3 libglib2.0-0 libgtk-3-0t64 \
            libasound2t64 libxrandr2 libpangocairo-1.0-0 libatk1.0-0 \
            libatk-bridge2.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 \
            libgdk-pixbuf2.0-0

      - name: Run Puppeteer test
        id: run-tests
        run: |
          npm test

      - name: Upload provider status
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: provider-status
          path: ./server/test/provider/status.json

  update-gist:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Download provider status artifact
        uses: actions/download-artifact@v4
        with:
          name: provider-status
          path: ./server/test/provider
      - name: Push provider status to Gist
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: node ./test/update-gist.js
